// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef _ESP32HMIINTERFACE_UI_H
#define _ESP32HMIINTERFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1084506651);    // assets/wind-vector.png
LV_IMG_DECLARE(ui_img_bebe_icon_png);    // assets/bebe icon.png
LV_IMG_DECLARE(ui_img_296721678);    // assets/settings icon (2).png
LV_IMG_DECLARE(ui_img_1497256624);    // assets/flecha abajo (2).png
LV_IMG_DECLARE(ui_img_145782787);    // assets/flecha arriba (3).png
LV_IMG_DECLARE(ui_img_1508956403);    // assets/back icon (1).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
