// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label39;
extern void ui_event_OxiButton2(lv_event_t * e);
extern lv_obj_t * ui_OxiButton2;
extern lv_obj_t * ui_DetectOxi;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

