// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_OxiButton2 = NULL;
lv_obj_t * ui_DetectOxi = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_OxiButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel15, 336);
    lv_obj_set_height(ui_Panel15, 129);
    lv_obj_set_x(ui_Panel15, -198);
    lv_obj_set_y(ui_Panel15, -140);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -296);
    lv_obj_set_y(ui_Label39, -183);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Pulse Oximetry");

    ui_OxiButton2 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_OxiButton2, 310);
    lv_obj_set_height(ui_OxiButton2, 30);
    lv_obj_set_x(ui_OxiButton2, -206);
    lv_obj_set_y(ui_OxiButton2, -183);
    lv_obj_set_align(ui_OxiButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OxiButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OxiButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_opa(ui_OxiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_OxiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectOxi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_DetectOxi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DetectOxi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DetectOxi, -202);
    lv_obj_set_y(ui_DetectOxi, -129);
    lv_obj_set_align(ui_DetectOxi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DetectOxi, "25.1");
    lv_obj_set_style_text_font(ui_DetectOxi, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -316);
    lv_obj_set_y(ui_Label5, -128);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "25.1");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OxiButton2, ui_event_OxiButton2, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Panel15 = NULL;
    ui_Label39 = NULL;
    ui_OxiButton2 = NULL;
    ui_DetectOxi = NULL;
    ui_Label5 = NULL;

}
