// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Spinbox2 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Spinbox3 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
// event funtions
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label14, target, "On", "Off");
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label11, target, "On", "Off");
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label12, target, "On", "Off");
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_opacity_set(ui_Panel6, 20);
        _ui_opacity_set(ui_Panel7, 1000);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_opacity_set(ui_Panel6, 1000);
        _ui_opacity_set(ui_Panel7, 20);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox3, -1);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox3, 1);
    }
}

void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
}

void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -334);
    lv_obj_set_y(ui_Label1, -213);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "IncuNest");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 376);
    lv_obj_set_height(ui_Panel1, 291);
    lv_obj_set_x(ui_Panel1, -201);
    lv_obj_set_y(ui_Panel1, -31);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 376);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -201);
    lv_obj_set_y(ui_Panel2, 174);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 86);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -118);
    lv_obj_set_y(ui_Switch1, 173);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 341);
    lv_obj_set_height(ui_Panel3, 107);
    lv_obj_set_x(ui_Panel3, 180);
    lv_obj_set_y(ui_Panel3, -110);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch2, 86);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -122);
    lv_obj_set_y(ui_Switch2, -151);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Switch3 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch3, 86);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 256);
    lv_obj_set_y(ui_Switch3, -143);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 336);
    lv_obj_set_height(ui_Panel4, 129);
    lv_obj_set_x(ui_Panel4, 184);
    lv_obj_set_y(ui_Panel4, 33);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 332);
    lv_obj_set_height(ui_Panel5, 96);
    lv_obj_set_x(ui_Panel5, 187);
    lv_obj_set_y(ui_Panel5, 163);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -291);
    lv_obj_set_y(ui_Label2, -150);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Temperature control");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -300);
    lv_obj_set_y(ui_Label3, 173);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Phototherapy");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 100);
    lv_obj_set_y(ui_Label4, -141);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Humidity control");

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 89);
    lv_obj_set_y(ui_Label5, -5);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Pulse Oximetry");

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_bebe_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -91);
    lv_obj_set_y(ui_Image2, 53);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 50);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -359);
    lv_obj_set_y(ui_Label6, -23);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Set");

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_1084506651);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -97);
    lv_obj_set_y(ui_Image4, -100);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 40);

    ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_296721678, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_296721678, NULL);
    lv_obj_set_width(ui_ImgButton1, 58);
    lv_obj_set_height(ui_ImgButton1, 58);
    lv_obj_set_x(ui_ImgButton1, 352);
    lv_obj_set_y(ui_ImgButton1, -201);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_TabView1, 262);
    lv_obj_set_height(ui_TabView1, 65);
    lv_obj_set_x(ui_TabView1, 181);
    lv_obj_set_y(ui_TabView1, 161);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Alarms");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "View details");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 157);
    lv_obj_set_y(ui_Label7, -90);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Set");

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -51);
    lv_obj_set_y(ui_Label11, -150);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Off");

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 324);
    lv_obj_set_y(ui_Label12, -144);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Off");

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -318);
    lv_obj_set_y(ui_Label13, -103);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "25.1");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -45);
    lv_obj_set_y(ui_Label14, 174);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Off");

    ui_Switch4 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, -112);
    lv_obj_set_y(ui_Switch4, -24);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 61);
    lv_obj_set_height(ui_Panel6, 28);
    lv_obj_set_x(ui_Panel6, -171);
    lv_obj_set_y(ui_Panel6, -23);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xA9ACF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -169);
    lv_obj_set_y(ui_Label9, -23);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Air");

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -316);
    lv_obj_set_y(ui_Label10, 48);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "28.3");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 73);
    lv_obj_set_y(ui_Label15, -103);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "50");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -239);
    lv_obj_set_y(ui_Label16, -23);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "C");

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 327);
    lv_obj_set_y(ui_Label17, -89);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "%");

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 61);
    lv_obj_set_height(ui_Panel7, 28);
    lv_obj_set_x(ui_Panel7, -54);
    lv_obj_set_y(ui_Panel7, -24);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xA9ACF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -52);
    lv_obj_set_y(ui_Label18, -24);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Skin");

    ui_Label19 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 99);
    lv_obj_set_y(ui_Label19, 37);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "0");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 289);
    lv_obj_set_y(ui_Label20, 37);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "lpm");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -266);
    lv_obj_set_y(ui_Label21, -103);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "C  /");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -261);
    lv_obj_set_y(ui_Label22, 48);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "C  /");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 110);
    lv_obj_set_y(ui_Label23, -102);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "%");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 137);
    lv_obj_set_y(ui_Label24, 36);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "%");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 226);
    lv_obj_set_y(ui_Label25, 38);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "160");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_Spinbox1, 50);
    lv_obj_set_height(ui_Spinbox1, 42);
    lv_obj_set_x(ui_Spinbox1, -212);
    lv_obj_set_y(ui_Spinbox1, -103);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 3, 2);
    lv_spinbox_set_range(ui_Spinbox1, 5, 800);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox1, 250);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 36);
    lv_obj_set_height(ui_Panel8, 32);
    lv_obj_set_x(ui_Panel8, -318);
    lv_obj_set_y(ui_Panel8, -22);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 36);
    lv_obj_set_height(ui_Panel9, 32);
    lv_obj_set_x(ui_Panel9, -270);
    lv_obj_set_y(ui_Panel9, -22);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinbox2 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_Spinbox2, 47);
    lv_obj_set_height(ui_Spinbox2, 42);
    lv_obj_set_x(ui_Spinbox2, 247);
    lv_obj_set_y(ui_Spinbox2, -89);
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox2, 2, 2);
    lv_spinbox_set_range(ui_Spinbox2, 0, 1000);
    lv_spinbox_set_cursor_pos(ui_Spinbox2, 2 - 1);
    lv_spinbox_set_value(ui_Spinbox2, 500);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 36);
    lv_obj_set_height(ui_Panel10, 32);
    lv_obj_set_x(ui_Panel10, 199);
    lv_obj_set_y(ui_Panel10, -89);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 36);
    lv_obj_set_height(ui_Panel11, 32);
    lv_obj_set_x(ui_Panel11, 296);
    lv_obj_set_y(ui_Panel11, -88);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton3 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1497256624, NULL);
    lv_obj_set_width(ui_ImgButton3, 20);
    lv_obj_set_height(ui_ImgButton3, 28);
    lv_obj_set_x(ui_ImgButton3, -320);
    lv_obj_set_y(ui_ImgButton3, -20);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton4 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_145782787, NULL);
    lv_obj_set_width(ui_ImgButton4, 22);
    lv_obj_set_height(ui_ImgButton4, 23);
    lv_obj_set_x(ui_ImgButton4, -271);
    lv_obj_set_y(ui_ImgButton4, -23);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_Spinbox3 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_Spinbox3, 50);
    lv_obj_set_height(ui_Spinbox3, 42);
    lv_obj_set_x(ui_Spinbox3, -208);
    lv_obj_set_y(ui_Spinbox3, 48);
    lv_obj_set_align(ui_Spinbox3, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox3, 3, 2);
    lv_spinbox_set_range(ui_Spinbox3, 5, 800);
    lv_spinbox_set_cursor_pos(ui_Spinbox3, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox3, 250);

    ui_ImgButton5 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1497256624, NULL);
    lv_obj_set_width(ui_ImgButton5, 20);
    lv_obj_set_height(ui_ImgButton5, 29);
    lv_obj_set_x(ui_ImgButton5, 197);
    lv_obj_set_y(ui_ImgButton5, -87);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_145782787, NULL);
    lv_obj_set_width(ui_ImgButton6, 25);
    lv_obj_set_height(ui_ImgButton6, 26);
    lv_obj_set_x(ui_ImgButton6, 295);
    lv_obj_set_y(ui_ImgButton6, -87);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Switch1 = NULL;
    ui_Panel3 = NULL;
    ui_Switch2 = NULL;
    ui_Switch3 = NULL;
    ui_Panel4 = NULL;
    ui_Panel5 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Image2 = NULL;
    ui_Label6 = NULL;
    ui_Image4 = NULL;
    ui_ImgButton1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_TabPage2 = NULL;
    ui_Label7 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Switch4 = NULL;
    ui_Panel6 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Panel7 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Spinbox1 = NULL;
    ui_Panel8 = NULL;
    ui_Panel9 = NULL;
    ui_Spinbox2 = NULL;
    ui_Panel10 = NULL;
    ui_Panel11 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton4 = NULL;
    ui_Spinbox3 = NULL;
    ui_ImgButton5 = NULL;
    ui_ImgButton6 = NULL;

}
